{% set name = "opentelemetry-instrumentation-sqlalchemy" %}
{% set version = "0.33b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-sqlalchemy-{{ version }}.tar.gz
  sha256: 00b0ca4af744e7f6ca66e07b16ef3dd3a2e795de99ba2e5aab78bfe11ee2a8e3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.33b0
    - opentelemetry-semantic-conventions ==0.33b0
    - python >=3.6
    - wrapt >=1.11.2
    # - sqlalchemy 
    # - pytest 
    - packaging >=21.0
    - opentelemetry-sdk ~=1.12
    # - sqlalchemy 
    # - pytest 
    # - sqlalchemy 
    # - pytest 
    # - sqlalchemy 
    # - pytest 
    # - sqlalchemy 
    # - pytest 
    # - sqlalchemy 
    # - pytest 
    # - sqlalchemy 
    # - pytest 

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-sqlalchemy
  summary: OpenTelemetry SQLAlchemy instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
