{% set name = "opentelemetry-instrumentation-sqlalchemy" %}
{% set version = "0.27b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-sqlalchemy-{{ version }}.tar.gz
  sha256: 8c77cea9641127aba5b34bf86c5b11f50cbadfe698b767f6f46f7e9fd35c3ede

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.27b0
    - opentelemetry-semantic-conventions ==0.27b0
    - python >=3.6
    - wrapt >=1.11.2
    # - sqlalchemy 
    # - pytest 
    - packaging >=21.0
    - opentelemetry-sdk ~=1.3
    # - sqlalchemy 
    # - pytest 

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-sqlalchemy
  summary: OpenTelemetry SQLAlchemy instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
