{% set name = "opentelemetry-instrumentation-sqlalchemy" %}
{% set version = "0.30b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-sqlalchemy-{{ version }}.tar.gz
  sha256: aaca5a96cbd33bd7cd6d548e02dd9a31fb06e6a78f291fb45c95f930af193bf0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.30b1
    - opentelemetry-semantic-conventions ==0.30b1
    - python >=3.6
    - wrapt >=1.11.2
    # - sqlalchemy 
    # - pytest 
    - packaging >=21.0
    - opentelemetry-sdk ~=1.3
    # - sqlalchemy 
    # - pytest 
    # - sqlalchemy 
    # - pytest 
    # - sqlalchemy 
    # - pytest 
    # - sqlalchemy 
    # - pytest 
    # - sqlalchemy 
    # - pytest 

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-sqlalchemy
  summary: OpenTelemetry SQLAlchemy instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
